### ISSUE TITLE
EditEntryInfoCommandTest seems to fail in certain cases

### ISSUE THREAD

**Issue by marvintxd** [CS2103-AY1819S1-W17-1/main#290]
`EditEntryInfoCommandTest` seems to fail for the tests:
1. `execute_allFieldsSpecifiedUnfilteredList_success()`
2. `execute_duplicateEntryUnfilteredList_failure()`

specifically when it's run after `AddBulletCommandTest`, specifically the method `execute_allFieldsSpecifiedUnfilteredList_success()` (when commented out, running tests in this sequence allows all to pass).

It is suspected that there may be an issue with `equals()` in `ResumeEntry` when that entry has been edited. 
For 1, the `expectedModel` and `actualModel` seem to deviate.
For 2, the command is supposed to fail in `command.execute()` as the `model.hasEntry(editedEntry)` should return `false`, but it returns `true` instead.

**Comment by marvintxd** [comment]
![image](https://user-images.githubusercontent.com/37933324/48154549-da334400-e303-11e8-9434-eeab591165d1.png)

Discovered the intermediate cause. The result of the `AddBulletCommand` from `AddBulletCommandTest` appears to have been carried over to this test.
<br/>
![image](https://user-images.githubusercontent.com/37933324/48155950-2633b800-e307-11e8-942e-a9da72407c93.png)

Without running `AddBulletCommandTest`, that entry in the `Model` indeed does not have that bullet description.

**Comment by jhengy** [comment]
I think the cause of the problem is because addBulletCommand is not pure. when I add bullet to an entry taken under `TypcialEntrys`, it modifies the global `ResumeEntry`constants, more specifically in our case, 
`WORK_FACEBOOK`.  So when it comes to EditEntryInfoCommandTest, the entryList of actual model already contains the entries updated with added description, and this is unknown to `EditEntryInfoCommandTest`. Under the test method `execute_allFieldsSpecifiedUnfilteredList_success()`, the `expectedModel` is only updated for the `EntryInfo` of the edited entry, not its bullet descriptions. This leads to failure in assertEquals
